kod:str = "ATCGATCGATCGATCGACTGACTAGTCATAGCTATGCATGTAGCTACTCGATCGATCGATCGATCGATCGATCGATCGATCGATCATGCTATCATCGATCGATATCGATGCATCGACTACTAT" 

kod1:str = "ATCGATCGATCGATCGACTGACTAGTCATAGCTATGCATGTAGCTACTCGATCGATCGA" +\
"TCGATCGATCGATCGATCGATCGATCATGCTATCATCGATCGATATCGATGCATCGACT" +\
"ACTAT"

kod2:str = "ATCGATCGATCGATCGACTGACTAGTCATAGCTATGCATGTAGCTACTCGATCGATCGA" 
kod2 += "TCGATCGATCGATCGATCGATCGATCATGCTATCATCGATCGATATCGATGCATCGACT" 
kod2 += "ACTAT"