genetski_kod:str = "AGTTCGTAAGATGTGTCC"
print(genetski_kod)
d:int = len(genetski_kod)
print(d)
broj_A:int = genetski_kod.count("A")
print(broj_A)
broj_G:int = genetski_kod.count("G")
print(broj_G)
broj_AG:int = genetski_kod.count("AG")
print(broj_AG)
broj_GA:int = genetski_kod.count("GA")
print(broj_GA)
